#!/bin/csh
#set echo
if $# == 2 then
	set date=$1
	set sdate=$2
else
	set date=`date +%Y%m%d`
	set sdate=`date +%y%m%d`
endif

gempak/doadv ${date} ${sdate}
gempak/doclouds ${date} ${sdate}
gempak/dorh ${date} ${sdate}
gempak/dotemp ${date} ${sdate}
gempak/dosurf ${date} ${sdate}
gempak/doprecip ${date} ${sdate}
fronts/newfronts ${date} 01
fronts/newfronts ${date} 04
fronts/newfronts ${date} 07
fronts/newfronts ${date} 10
fronts/newfronts ${date} 13
fronts/newfronts ${date} 16
fronts/newfronts ${date} 19
fronts/newfronts ${date} 22
