#!/bin/csh
set date=`date --date='15 days ago' +%y%m%d`
cd ~/projects/forecast/gempak/data
rm *[a-z_\.]${date}*
cd ~/projects/forecast/fcst/raw
rm *[a-z_\.]${date}*
cd ~/projects/forecast/merge/out
rm ${date}.out
cd /fcst
rm ${date}.out
