#!/bin/csh
cd ~/projects/forecast/gempak
if $# == 2 then
	set date=$1
	set sdate=$2
else
	set date=`date -u +%y%m%d`
	set sdate=`date -u +%Y%m%d`
endif

./temp_script 00 ${date} ${sdate}
./get_data data/tf${sdate}_00
mv data/tf${sdate}_00.list fcst/raw

./temp_script 12 ${date} ${sdate}
./get_data data/tf${sdate}_12
mv data/tf${sdate}_12.list fcst/raw
