#!/bin/csh 
########################################################
#
# Can be run from cron.
# The first argument should be the target hour
# 
########################################################
#
# source the 5.2 environment variables 
#
source /usr/local/nawips/Gemenviron

# Set the root Ntrans directory
#
# setenv NTRANSHOME ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd data

# Define current date
#
#set yy=`date -u +%y`
#set mm=`date -u +%m`
#set dd=`date -u +%d`
#set date=${yy}${mm}${dd}
#setenv OLD $TZ
#setenv TZ FOO24BAR
#set yesterday=`date +%y%m%d`
#setenv TZ $OLD

# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/surface/sao
setenv LOGFILE log_surface

# Remove last hour's log file
rm -f log_surface

# Set some variables for GPMAP run
#
set grid=${DATA_DIR}/${1}_sao.gem
set tmp=${grid:r}
set time=${tmp:t}
sleep 15

#
# Run sflist to extract precipitation amounts
#
$GEMEXE/sflist << EOF >> $LOGFILE
\$RESPOND = YES
SFFILE	= $grid
SFPARM	= p03i;p06i;p09i;p12i;p18i;p24i
AREA	= 25;-125;50;-65
DATTIM	= /00-/12
OUTPUT	= f/precip${2}_00
run

exit
EOF

$GEMEXE/sflist << EOF >> $LOGFILE
\$RESPOND = YES
DATTIM	= /13-/23
OUTPUT	= f/precip${2}_13
run

exit
EOF

foreach hour (00 13)
# Convert the files just made into tab-separated text
	sed -e '1,$s/  */	/g' precip${2}_${hour} | cut -f2- > tmp.$$
	mv tmp.$$ precip${2}_${hour}

# add each station's many values, so there is only one report per station
	perl ../clean_precip.pl < precip${2}_${hour} | sort > tmp.$$
	mv tmp.$$ precip${2}_${hour}
end
